### ISSUE TITLE
Adding an event - date and time selection

### ISSUE THREAD

**Issue by simmonspaul** [Roomify/bat_drupal#16]
I setup an event type that can be booked hourly.

When I add an event, the first section to fill out is EVENT DATES.

Within that section are four boxes,  2 rows by 2 columns.
There are no labels to these boxes.
When you click in the boxes in the top column you get a pop up calendar to enter the day.

The boxes in the 2nd row are intended for the time.

It would be nice if there were labels.
It would be nice if these labels were customisable.
There is a constraint now that the finish date needs to be greater than the start date (which is not desirable for hourly bookings).
It would be preferred for the finish date to be hidden or optional (most hourly booking use cases will be same day).
Typical users can't fathom military time and therefore something more user friendly might include am/pm.

Thanks
Paul

**Comment by istos** [comment]
Hi Paul - those are all great comments and definitely worth considering. What are your dev skills like - would be happy to point you in the right direction and help because we will be super happy to see pull requests :-)
If you have time to do some mockups those would be great help as well to get the ideas across more immediately.

**Comment by simmonspaul** [comment]
Thanks. I'd be willing to try but would never consider myself a developer. Never worked in git before. Would you be so kind as to talk me through where to fix #15 myself? That will be a good starting point.

Also is there a forum or place where there is some discussion on the bat module, rather than via "issues".

**Comment by acrollet** [comment]
Hi @simmonspaul,

thanks for the feedback - I ended up fixing #15, it comes down to how the [Entity API module](https://www.drupal.org/project/entity) behaves rather than a simple typo. 

The end date no longer has to be greater than the start date, please ensure you're testing on the latest state of the code from github - 7.x-1.x of bat_drupal and 7.x-2.x of bat_api.

We're very happy to have your help and feedback in testing these things but please keep in mind a couple of things:
- this is a very early alpha release and it is not necessarily ready for production use
- because BAT is meant to be a very general tool for handling all kinds of use cases and applications, we expect that the layer you're seeing (e.g. when creating events) will often be abstracted away for end users. It's important to keep the UI very basic and generalized so that it will continue to work for all use cases. This is why we would love to see any mockups, even if it's just a marked up screenshot. This will help us understand your use case while we try to ensure that all possible use cases continue to be supported.

**Comment by simmonspaul** [comment]
Roger that. I understand it is an alpha release. 
However, I liked the maturity of the Rooms module, the core functionality is proven and the bones are good.
The abstracted approach that is being taken for BAT is far more interesting to me as it will be more easily applied to multiple use cases.

There is more than one way to skin a cat and I was making quite some good progress using entityform, the rules module (creating users / profile2s, associated availability calendars, and the population of clients in the commerce module). The Rooms module seemed to have similar functionality and I did like the look and feel of fullcalendar.

The most complex use case that I can think of involves a tutoring company.
I have students and teachers (I set these up as users with profile2 for field attributes specific to each).
I need to book them for variably length of tutoring sessions from 30-120 minutes with each other, and then in one of our rooms. In that case, I have three "availabilities" that need to match up!
Consider also the factors or filters that need to be considered to match students and teachers, eg. teachables (subjects) and academic level (or grade). Anyways that is my fun...
